server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: inventory-route
          uri: ${INVENTORY_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/products/**
          filters:
            - AddRequestHeader=X-Gateway-Source, api-gateway

        - id: order-route
          uri: ${ORDER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/orders/**
          filters:
            - AddRequestHeader=X=Gateway-Source, api-gateway

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.warehouse: DEBUG
    org.spring.framework.cloud.gateway: INFO